### ISSUE TITLE
Where is the document split module code, including small2big and sliding window

### ISSUE THREAD

**Issue by caopeizhi-research** [FudanDNN-NLP/RAG#1]
Where is the document split module code, including small2big and sliding window

**Comment by OmriLevyTau** [comment]
I'm also interested to see what where you referring by saying "sliding window" chunking.
Thank you!

**Comment by zhenghuawang6** [comment]
thanks for your reminder,We have uploaded the initial version of the code for chunk testing, including small2big and sliding window.
