### ISSUE TITLE
Why not use bge reranker model which is more common in reranking phase

### ISSUE THREAD

**Issue by vikotse** [FudanDNN-NLP/RAG#2]
Thanks for the great paper on providing practice performance on RAG in each phase.
And I have a question: why not include bge reranker model which is more common in the reranking phase?
The comparison between this model and other models will be instructive.
https://huggingface.co/BAAI/bge-reranker-large

**Comment by Shadowlized** [comment]
Code for reranking with 'bge-reranker-v2-m3' is added to the repository (named as "BGE" in retrieval_config["rerank_model"])
