### ISSUE TITLE
Missing "bm25_index" file for LuceneSearcher Initialization

### ISSUE THREAD

**Issue by BierOne** [FudanDNN-NLP/RAG#8]
Hi! 

Thanks for the sharing of this outstanding work! I am trying to reproduce the results presented in the paper. However, I found that one file, "bm25_index," is missing for the initialization of LuceneSearcher.

Could you please help in this regard? Thanks in advance.

You can refer to here for the details: https://github.com/FudanDNN-NLP/RAG/blob/af3c95232ce61d900a9f54ba1e887881b3495f43/opencompass/JointTest/retrieval/queries2retrievers.py#L258

**Comment by xgao922** [comment]
Hi!

Thank you for your interest in our work and for bringing this to our attention.

The folder `bm25_index` mentioned in the code refers to a pre-built BM25 index, which can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1UVH2_lLdhTa6okASThyBEkE7R9Ll5mTf?usp=drive_link). Once the index is downloaded, you can use LuceneSearcher to point to the directory containing the index.

We also have provided the script `build_bm25_index.sh`, which you can use to create the index for your custom document collection. 

To use the script, you need to specify the following arguments:

- `input`: The path to your custom document collection.
- `index`: The directory where the generated index will be stored.

For detailed instructions on building a BM25 index, please refer to the official Pyserini documentation: [Building a BM25 Index (Direct Java Implementation)](https://github.com/castorini/pyserini/blob/master/docs/usage-index.md#building-a-bm25-index-direct-java-implementation).

Thank you again for your support, and please feel free to reach out if you have any further questions!

**Comment by xgao922** [comment]
Hi!

Thank you for your interest in our work and for bringing this to our attention.

The folder `bm25_index` mentioned in the code refers to a pre-built BM25 index, which can be downloaded from [Google Drive](https://drive.google.com/drive/folders/1UVH2_lLdhTa6okASThyBEkE7R9Ll5mTf?usp=drive_link). Once the index is downloaded, you can use LuceneSearcher to point to the directory containing the index.

We have also provided the script `build_bm25_index.sh`, which you can use to create the index for your custom document collection. 

To use the script, you need to specify the following arguments:

- `input`: The path to your custom document collection.
- `index`: The directory where the generated index will be stored.

For detailed instructions on building a BM25 index, please refer to the official Pyserini documentation: [Building a BM25 Index (Direct Java Implementation)](https://github.com/castorini/pyserini/blob/master/docs/usage-index.md#building-a-bm25-index-direct-java-implementation).

Thank you again for your support, and please feel free to reach out if you have any further questions!

**Comment by BierOne** [comment]
Glad to hear that. Thank you!
